---
# Settings for the bootserver

tty_server:
  # Enable this if you want to log in to the raspberry pi and connect
  # to the serial terminal.
  enabled: true
  user: terminal
  password: terminal
  # set device to the terminal device connected to the server, 
  # which will usually be /dev/ttyUSB<n>  
  device: /dev/ttyUSB3
  # Configuration for Serial Port A on a Sun 3/60 in diag mode
  # is 9600, 8, none, 1; with no flow control
  baudrate: 9600
  databits: 8
  parity: none
  stopbits: 1  
  flow: none


pi:
  # Configuration for the Raspberry Pi server itself.
  ether_ip_addr:  192.168.0.1
  ether_ip_maskbits: 24

sun3:
  # if you have a 3/80 or 3/460, set is_sun3x to true.
  # I don't have one, so I can't test it.  Feel free to submit patches.
  is_sun3x:  false
  mac_address: 08:00:20:00:4E:BD
  hostname: mysun3
  ip_addr: 192.168.0.2
  swapfile: 64M
