---
- name: Install Sun3 Bootserver
  hosts: localhost
  connection: local
  tasks:
  - name: Load settings from settings.yml
    include_vars:
      name: settings      
      file: ../settings.yml

  - name: Install Packages
    apt:
      pkg:
        - wget
        - curl      
        - tftpd-hpa
        - rarpd
        - bootparamd      
        - nfs-kernel-server
      state: present


  - name: Setup Pi Networking
    include_tasks: setup_pi_network.yml
    
  - name: Download the SunOS 4.1.1 Distribution(s)
    include_tasks: download_sunos_distribution.yml
    when: settings.sun3.os == "sunos"

  - name: Download NetBSD Distribution
    include_tasks: download_netbsd_distribution.yml
    when: settings.sun3.os == "netbsd"

  - name: Setup NFS root
    include_tasks: setup_nfsroot.yml

  - name: Setup Bootservers
    include_tasks: setup_bootservers.yml



  - name: Do the ttyserver setup
    include_tasks: install_ttyserver.yml
    when: settings.tty_server.enabled