---
- name: Set up /etc/ethers
  lineinfile:
    path: /etc/ethers
    line: "{{ settings.sun3.mac_address }}      {{ settings.sun3.ip_addr }}"
    state: present
    regex: "^{{ settings.sun3.mac_address }}"
    create: yes

- name: Restart RARPD
  systemd:
    name: rarpd.service
    state: restarted

- name: Copy boot image
  shell: ./link_bootfile.py {{ 'boot.sun3x' if settings.sun3.is_sun3x else 'boot.sun3' }} {{ settings.sun3.ip_addr }}
  
- name: Set TFTP server options
  lineinfile:
    path: /etc/default/tftpd-hpa
    line: TFTP_OPTIONS="-vvv --secure"
    regex: ^TFTP_OPTIONS
  register: tftp_options

- name: Set TFTP bind address
  lineinfile:
    path: /etc/default/tftpd-hpa
    line: TFTP_ADDRESS={{ settings.pi.ether_ip_addr }}:69
    regex: ^TFTP_ADDRESS
  register: tftp_address

- name: Restart tftpd
  systemd:
    name: tftpd-hpa.service
    state: restarted
  when: tftp_options.changed or tftp_address.changed

- name: Add host to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ settings.sun3.ip_addr }}  {{ settings.sun3.hostname }}"
    regex: "^{{ settings.sun3.ip_addr }}"

- name: enabled debugging on rpcbind
  lineinfile:
    path: /etc/default/rpcbind
    line: OPTIONS="-w -d -r -i -h {{ settings.pi.ether_ip_addr }}"
    regex: ^OPTIONS
  register: rpcbind_config

- name: restart rpcbind
  systemd:
    name: rpcbind
    state: restarted
  when: rpcbind_config.changed

- name: Generate bootparam config line
  shell: ./generate_bootparam.py {{ settings.sun3.hostname }} {{ settings.pi.ether_ip_addr }} {{ settings.pi.ether_ip_maskbits }}
  register: bootparamd_config

- name: Configure bootparams
  lineinfile:
    path: /etc/bootparams
    create: yes
    regex: ^{{ settings.sun3.hostname }}\s
    line: "{{ bootparamd_config.stdout }}"
  register: bootparamd

- name: Restart bootparamd
  systemd:
    name: bootparamd.service
    state: restarted
  when:  bootparamd.changed

- name: Enable NFSv2
  lineinfile:
    path: /etc/default/nfs-kernel-server
    line: RPCNFSDOPTS="--nfs-version 2,3,4 --debug --syslog"
    regex: ^RPCNFSDOPTS
  register:  kernel_nfs

- name: Restart Kernel NFS server
  systemd:
    name: nfs-server
    state: restarted
  when: kernel_nfs.changed

- name: Configure NFS root export to client
  lineinfile:
    path: /etc/exports
    line: /srv/nfsroot/{{ settings.sun3.hostname }}  {{ settings.sun3.ip_addr }}(rw,insecure,no_root_squash,no_subtree_check)
    regex: ^/srv/nfsroot/{{settings.sun3.hostname}}\s
  register: nfs_root_export

- #name: Configure NFS swapfile export to client
  #lineinfile:
  #  path: /etc/exports
  #  line: /srv/nfsroot/{{ settings.sun3.hostname }}/swapfile  {{ settings.sun3.ip_addr }}(rw,insecure,no_root_squash,no_subtree_check)
  #  regex: ^/srv/nfsroot/{{settings.sun3.hostname}}/swapfile\s
  #register: nfs_swap_export  

- name: Export filesystems
  #when: nfs_swap_export.changed or nfs_root_export.changed
  when: nfs_root_export.changed
  shell: exportfs -a
  ignore_errors: true
