---
- name: Create NFS root for all machines
  file:
    path: /srv/nfsroot
    state: directory

- name: Check if the NFS root for this machine already exists
  stat:
    path: /srv/nfsroot/{{ settings.sun3.hostname }}
  register: nfs_client_root

- name: Create NFS root for this machine
  file:
    path: /srv/nfsroot/{{ settings.sun3.hostname }}
    state: directory
  when: not nfs_client_root.stat.exists

- name: Unpack Sun3 Distribution in NFS root
  shell: ./unpack_sunos_sun3.sh /srv/nfsroot/{{ settings.sun3.hostname }}
  when: settings.sun3.os == "sunos" and (not settings.sun3.is_sun3x and not nfs_client_root.stat.exists)

# This isn't implemented.  Feel free to do so.
- name: Unpack Sun3x Distribution in NFS root
  shell: ./unpack_sunos_sun3x.sh /srv/nfsroot/{{ settings.sun3.hostname }}
  when: settings.sun3.os == "sunos" and settings.sun3.is_sun3x and not nfs_client_root.stat.exists

- name: Unpack NetBSD Distribution in NFS root
  shell: ./unpack_netbsd.sh /srv/nfsroot/{{ settings.sun3.hostname }} 
  when: settings.sun3.os == "netbsd" and not nfs_client_root.stat.exists


- name: Create the swapfile
  shell: dd if=/dev/zero of=/srv/nfsroot/{{ settings.sun3.hostname }}/swapfile bs={{ settings.sun3.swapfile }} count=1
  when: not nfs_client_root.stat.exists


