---
- name: Create NFS root for all machines
  file:
    path: /srv/nfsroot
    state: directory

- name: Create NFS root for this machine
  file:
    path: /srv/nfsroot/{{ settings.sun3.hostname }}
    state: directory
  

- name: Unpack Sun3 Distribution in NFS root
  shell: ./unpack_sun3.sh /srv/nfsroot/{{ settings.sun3.hostname }}
  when: not settings.sun3.is_sun3x

# This isn't implemented.  Feel free to do so.
- name: Unpack Sun3x Distribution in NFS root
  shell: ./unpack_sun3x.sh /srv/nfsroot/{{ settings.sun3.hostname }}
  when: settings.sun3.is_sun3x

- name: Create the swapfile
  shell: dd if=/dev/zero of=/srv/nfsroot/{{ settings.sun3.hostname }}/swapfile bs={{ settings.sun3.swapfile }} count=1


